# Generated by Django 5.2.1 on 2025-12-10 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_length', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=100)),
                ('last_name', models.CharField(default='Doe', max_length=100)),
                ('current_role', models.CharField(max_length=200)),
                ('desired_role', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date_applied', models.DateField(auto_now=True)),
                ('follow_up', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('resume', models.FileField(upload_to='resume/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover-letter/')),
                ('job_status', models.CharField(choices=[('A', 'Applied'), ('I', 'Interviewed'), ('R', 'Rejected'), ('H', 'Hired')], max_length=1)),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.jobuser')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('responsibilities', models.TextField()),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='jobapp.jobuser')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('HS', 'High School Diploma'), ('AS', "Associate's Degree"), ('B', "Bachelor's Degree"), ('M', "Master's Degree")], max_length=2)),
                ('degree_field', models.CharField(max_length=200)),
                ('is_graduated', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('school', models.CharField(max_length=200)),
                ('graduation_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('graduation_year', models.IntegerField()),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='jobapp.jobuser')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('tool', 'Tools'), ('soft', 'Soft Skill'), ('language', 'Languages'), ('technical', 'Technical Skill')], max_length=20)),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobapp.jobuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_resume', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('liked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.jobuser')),
            ],
        ),
    ]
