# Generated by Django 5.2.1 on 2025-05-16 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_length', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_role', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('desired_role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date_applied', models.DateField(auto_now=True)),
                ('follow_up', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('resume', models.FileField(upload_to='resume/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover-letter/')),
                ('job_status', models.CharField(choices=[('A', 'Applied'), ('I', 'Interviewed'), ('R', 'Rejected'), ('H', 'Hired')], max_length=1)),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.jobuser')),
            ],
        ),
    ]
