# Generated by Django 5.2.1 on 2025-12-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='jobuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('tool', 'Tools'), ('language', 'Languages'), ('technical', 'Technical Skill'), ('soft', 'Soft Skill')], max_length=20),
        ),
    ]
