# Generated by Django 5.2.1 on 2026-01-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_remove_jobuser_first_name_remove_jobuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Skill'), ('language', 'Languages'), ('soft', 'Soft Skill'), ('tool', 'Tools')], max_length=20),
        ),
    ]
