# Generated by Django 5.2.1 on 2026-01-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_status',
            field=models.CharField(choices=[('A', 'Applied'), ('I', 'Interviewed'), ('O', 'Offered'), ('R', 'Rejected'), ('H', 'Hired')], max_length=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Languages'), ('technical', 'Technical Skill'), ('soft', 'Soft Skill'), ('tool', 'Tools')], max_length=20),
        ),
    ]
