# Generated by Django 5.2.1 on 2025-05-23 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_usertemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('HS', 'High School Diploma'), ('AS', "Associate's Degree"), ('B', "Bachelor's Degree"), ('M', "Master's Degree")], max_length=2)),
                ('degree_field', models.CharField(max_length=200)),
                ('is_graduated', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('school', models.CharField(max_length=200)),
                ('graduation_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('graduation_year', models.IntegerField()),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.jobuser')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('responsibilities', models.TextField()),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.jobuser')),
            ],
        ),
    ]
