# Generated by Django 5.2.1 on 2025-05-26 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_education_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('language', 'Languages'), ('soft', 'Soft Skill'), ('tool', 'Tools'), ('technical', 'Technical Skill')], max_length=20)),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.jobuser')),
            ],
        ),
    ]
