# Generated by Django 5.2.1 on 2026-02-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_alter_jobapplication_job_status_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Skill'), ('tool', 'Tools'), ('language', 'Languages'), ('soft', 'Soft Skill')], max_length=20),
        ),
    ]
