# Generated by Django 5.2.1 on 2026-03-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewnote',
            name='job_application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interview_notes', to='jobapp.jobapplication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Languages'), ('soft', 'Soft Skill'), ('tool', 'Tools'), ('technical', 'Technical Skill')], max_length=20),
        ),
    ]
