# Generated by Django 5.2.1 on 2026-03-05 20:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewnote',
            name='job_application',
            field=models.ForeignKey(default=datetime.datetime(2026, 3, 5, 20, 54, 10, 375629, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='interview_notes', to='jobapp.jobapplication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('soft', 'Soft Skill'), ('technical', 'Technical Skill'), ('language', 'Languages'), ('tool', 'Tools')], max_length=20),
        ),
    ]
