# Generated by Django 5.2.1 on 2026-03-05 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_interviewnote_job_application_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewnote',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 5, 21, 37, 45, 777070, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('soft', 'Soft Skill'), ('tool', 'Tools'), ('language', 'Languages'), ('technical', 'Technical Skill')], max_length=20),
        ),
    ]
