# Generated by Django 5.2.1 on 2026-03-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_interviewnote_date_and_time_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewnote',
            name='interview_type',
            field=models.CharField(choices=[('Phone', 'Phone Interview'), ('Zoom', 'Zoom Interview'), ('Onsite', 'Onsite Interview')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Skill'), ('soft', 'Soft Skill'), ('language', 'Languages'), ('tool', 'Tools')], max_length=20),
        ),
    ]
