# Generated by Django 5.2.1 on 2025-05-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_alter_education_jobuser_alter_experience_jobuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobuser',
            name='first_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='jobuser',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Skill'), ('language', 'Languages'), ('soft', 'Soft Skill'), ('tool', 'Tools')], max_length=20),
        ),
    ]
