# Generated by Django 5.2.1 on 2025-05-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_jobuser_first_name_jobuser_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='field',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Languages'), ('soft', 'Soft Skill'), ('tool', 'Tools'), ('technical', 'Technical Skill')], max_length=20),
        ),
    ]
