# Generated by Django 5.2.1 on 2026-03-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_interviewnote_interview_type_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewnote',
            name='interview_type',
            field=models.CharField(choices=[('Phone', 'Phone Interview'), ('Zoom', 'Zoom Interview'), ('Onsite', 'Onsite Interview')], default='Phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Languages'), ('tool', 'Tools'), ('soft', 'Soft Skill'), ('technical', 'Technical Skill')], max_length=20),
        ),
    ]
