# Generated by Django 5.2.1 on 2026-03-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_alter_interviewnote_interview_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interviewed', 'Interviewed'), ('Offered', 'Offered'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Languages'), ('soft', 'Soft Skill'), ('technical', 'Technical Skill'), ('tool', 'Tools')], max_length=20),
        ),
    ]
