# Generated by Django 5.2.1 on 2025-05-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_rename_field_experience_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Skill'), ('soft', 'Soft Skill'), ('tool', 'Tools'), ('language', 'Languages')], max_length=20),
        ),
    ]
