# Generated by Django 5.2.1 on 2025-05-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('tool', 'Tools'), ('language', 'Languages'), ('technical', 'Technical Skill'), ('soft', 'Soft Skill')], max_length=20),
        ),
    ]
