# Generated by Django 5.2.1 on 2026-03-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_alter_jobapplication_job_status_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('soft', 'Soft Skill'), ('language', 'Languages'), ('tool', 'Tools'), ('technical', 'Technical Skill')], max_length=20),
        ),
    ]
