# Generated by Django 5.2.1 on 2026-03-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewnote',
            name='interview_outcome',
            field=models.CharField(choices=[('Accepted Offer', 'Accepted Offer'), ('Rejected Offer', 'Rejected Offer'), ('Rejected', 'Rejected'), ('No Response', 'No Response')], default='No Response', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('soft', 'Soft Skill'), ('technical', 'Technical Skill'), ('language', 'Languages'), ('tool', 'Tools')], max_length=20),
        ),
    ]
