# Generated by Django 5.2.1 on 2026-03-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_interviewnote_interview_outcome_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Skill'), ('soft', 'Soft Skill'), ('tool', 'Tools'), ('language', 'Languages')], max_length=20),
        ),
    ]
