# Generated by Django 5.2.1 on 2026-03-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='media/'),
        ),
    ]
