# Generated by Django 5.2.1 on 2026-03-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0015_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media/resume'),
        ),
    ]
