# Generated by Django 5.2.1 on 2026-03-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
