# Generated by Django 5.2.1 on 2026-03-31 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_alter_usertemplate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='city',
            field=models.CharField(default='Dallas', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_ended',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_started',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='experience',
            name='state',
            field=models.CharField(default='Texas', max_length=100),
        ),
    ]
