# Generated by Django 5.2.1 on 2026-04-09 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_experience_city_experience_date_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewnote',
            name='jobuser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.jobuser'),
        ),
    ]
