# Generated by Django 5.2.1 on 2026-04-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_interviewnote_jobuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewnote',
            name='jobuser',
        ),
    ]
